# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Zhekai Jiang
tagline:          'Bachelor of Software Engineering (B.S.E.) Student, Research Assistant, TEAM Mentor & Grader @ McGill University'
description:      '<a href="https://www.mcgill.ca/study/2019-2020/faculties/engineering/undergraduate/programs/bachelor-software-engineering-bse-software-engineering" target="_blank">Bachelor of Software Engineering (B.S.E.)</a> Student, Research Assistant, <a href="https://www.mcgill.ca/tpulse/tomlinson-engagement-award-mentoring-team" target="_blank">TEAM Mentor</a> & Grader @ <a href="https://www.mcgill.ca" target="_blank">McGill University</a>'
url:              https://zhekai-jiang.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
                                
remote_theme: fongandrew/hydeout
